from os.path import join

wildcard_constraints:
    patient="Pt0",
    sample="GSM3454528|GSM3454529",
    celltype="Monocyte",

include: "../rules/common.smk"
include: "../rules/analysis-10x.smk"

FIGURE_1B = join("output", "plots", "figure_1B.pdf")
FIGURE_2B = join("output", "plots", "figure_2B.pdf")


rule all:
    input:
        FIGURE_1B,
        FIGURE_2B


### Rules for Figures ###

# genera piechart
rule plot_figure_2B:
    input:
        PATIENT_MICROBE_READ_TABLE.format(kingdom="All", method="PathSeq",
               patient="Pt0", tax_level="genus"),
        PATIENT_PATHSEQ_TAXID_MAP.format(kingdom="All", method="PathSeq",
               patient="Pt0"),
        PATIENT_SAMPLE_METADATA.format(kingdom="All", method="PathSeq",
               patient="Pt0", tax_level="genus"),
    output:
        FIGURE_2B
    script:
        "src/plot_figure_2B.py"


rule plot_figure_1B:
    input:
        PATIENT_MICROBE_READ_TABLE.format(kingdom="All", method="PathSeq",
               patient="Pt0", tax_level="genus"),
        PATIENT_SAMPLE_METADATA.format(kingdom="All", method="PathSeq",
               patient="Pt0", tax_level="genus"),
        PATIENT_PATHSEQ_TAXID_MAP.format(kingdom="All", method="PathSeq",
               patient="Pt0"),
    output:
        FIGURE_1B
    script:
        "src/plot_figure_1B.R"


# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Ben-Moshe2019/output/ data/
# rsync -avc --include='raw_feature_bc_matrix.h5' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Ben-Moshe2019/ data/
