from os.path import join
import pandas as pd

wildcard_constraints:
    patient="4196",

# parameters
include: "../rules/STARsolo.smk"
include: "../rules/common.smk"
#include: "../rules/stats.smk"
#include: "../rules/spikein.smk"
#include: "../rules/plotting.smk"
#include: "../rules/nreads_sample_size_analysis.smk"
plates = ["P1", "P2", "P3", "P4", "P5"]

units = pd.read_csv("data/units.tsv", sep="\t", dtype={"patient": "str", "sample": "str"})

PATIENT_INFECTION_MICROBE_READ_TABLE = join("output", "{patient}_{infection}_{tax_level}_{method}_{kingdom}_reads.tsv")
PATIENT_INFECTION_SAMPLE_METADATA = join("output", "{patient}_{infection}_{tax_level}_{method}_{kingdom}_metadata.tsv")
PATIENT_INFECTED_MICROBE_READ_TABLE = join("output", "{patient}_{infected}_{tax_level}_{method}_{kingdom}_reads.tsv")
PATIENT_INFECTED_SAMPLE_METADATA = join("output", "{patient}_{infected}_{tax_level}_{method}_{kingdom}_metadata.tsv")

INFECTION_TTEST_MARKERS = join("output", "t-test-{patient}-{infection}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
INFECTION_WILCOX_MARKERS = join("output", "wilcox-{patient}-{infection}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
INFECTED_TTEST_MARKERS = join("output", "t-test-{patient}-{infected}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
INFECTED_WILCOX_MARKERS = join("output", "wilcox-{patient}-{infected}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")

PATIENT_MICROBE_READ_TABLE = join("output", "{patient}_{tax_level}_{method}_{kingdom}_reads.tsv")
PATIENT_SAMPLE_METADATA = join("output", "{patient}_{tax_level}_{method}_{kingdom}_metadata.tsv")

PATIENT_HUMAN_MICROBE_READ_TABLE = join("output", "{patient}_human_{kingdom}_{tax_level}_{method}_reads.tsv")

# SAMPLE_SIZE_PLOT = join("output", "sigpercentage-wilcox-{patient}_{celltype}_{celltype_of_interest}_{celltype_comparison}_{tax_level}_{method}_{kingdom}_{nsamples}_{mincells}_{maxcells}_{norm}_{pvaltype}.pdf")
WILCOX_PLATE_CONTAMINANTS = join("output", "contaminants-wilcox-{patient}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")

TTEST_MARKERS = join("output", "t-test-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
WILCOX_MARKERS = join("output", "wilcox-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
BINOM_MARKERS = join("output", "binomial-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")

PATIENT_TTEST_MARKERS = join("output", "t-test-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
PATIENT_WILCOX_MARKERS = join("output", "wilcox-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")
PATIENT_BINOM_MARKERS = join("output", "binomial-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{kingdom}-{pvaltype}-{lfc}-{block}.tsv")



rule all:
    input:
        expand(PATIENT_STARsolo_READCOUNT, patient="4196")
        # expand(PATIENT_MICROBE_READ_TABLE, patient="4196", kingdom="Bacteria",
        #        tax_level=["superkingdom", "phylum", "class", "order", "family", "genus", "species"],
        #        method="PathSeq")
        # expand(PATIENT_WILCOX_MARKERS, patient="Pt0", kingdom=["Bacteria", "Viruses"], tax_level=["superkingdom", "phylum", "class", "order", "family", "genus", "species"],
        #        method="PathSeq", norm="spike", celltype="infected",
        #        celltype_of_interest="infected", block="plate", pvaltype="all", lfc=["0"]),
        # expand(PATIENT_WILCOX_MARKERS, patient="Pt0", kingdom=["Bacteria"], tax_level=["phylum", "class", "order", "family", "genus", "species"],
        #        method="PathSeq", norm="deconv", celltype="infected",
        #        celltype_of_interest="infected", block="plate", pvaltype="all", lfc=["0.5"]),
        # expand(PATIENT_WILCOX_MARKERS, patient="Pt0", kingdom=["Bacteria", "Viruses"], tax_level=["genus", "species"],
        #        method="PathSeq", norm="spike", celltype="infection",
        #        celltype_of_interest="LT2", block="plate", pvaltype="all", lfc=["0.5"]),
        #expand(DECONV_NORM_PLOT, patient="Pt0", celltype=["status"], kingdom="Bacteria", tax_level="strain", method="PathSeq", microbe=["Salmonella_enterica_subsp._enterica_serovar_Typhimurium_str._LT2", "Salmonella_enterica_subsp._enterica_serovar_Typhimurium_str._D23580"]),
        # expand(WILCOX_PLATE_CONTAMINANTS, tax_level=["genus", "species"], kingdom="Bacteria",
        #        method="PathSeq", patient="Pt0",
        #        celltype="status", lfc="0.5",
        #        norm=["spike"], pvaltype="all", block="status"),
        # expand(READ_SAMPLE_SIZE_PLOT, patient="Pt0",
        #        celltype="infected", celltype_of_interest="infected",
        #        celltype_comparison="bystander", tax_level="species",
        #        method="PathSeq", kingdom="Bacteria",
        #        microbe="Salmonella_enterica", pvaltype="all", block="plate",
        #        lfc="1", norm=["deconv", "spike"], minreads=1000, maxreads=2500, nsamples=100)
        # expand(PATIENT_TTEST_MARKERS, tax_level=["superkingdom"], kingdom="Bacteria",
        #        method="PathSeq", patient="Pt0", celltype="infected", lfc="0",
        #        celltype_of_interest=["infected"], norm=["deconv"], pvaltype="any", block="plate"),
        # expand(TTEST_MARKERS, tax_level=["strain"], kingdom="Bacteria",
        #        method="PathSeq", patient="Pt0", celltype="status", lfc="0.5",
        #        celltype_of_interest=["D23580-infected", "LT2-infected"], norm=["deconv"], pvaltype="all", block="plate"),
        # expand(TTEST_SPIKE_MARKERS, tax_level=["genus", "phylum", "species", "strain"], kingdom="Bacteria",
        #        method="PathSeq", patient="Pt0", celltype="infected", lfc=1,
        #        celltype_of_interest="infected", norm="spike", pvaltype="any"),
        # expand(WILCOX_PLATE_CONTAMINANTS, tax_level=["species"], kingdom="Bacteria",
        #        method="PathSeq", patient="Pt0", celltype="plate", lfc=[.5, 1, 0],
        #        norm=["spike", "deconv"], pvaltype="any", block="infected"),




rule convert_PathSeq_to_read_counts:
    wildcard_constraints:
        method="PathSeq"
    params:
        join("data", "PathSeq", "{}-{}-{}-{}", "pathseq.txt")
    input:
        "data/units.tsv",
    output:
        PATIENT_MICROBE_READ_TABLE,
        PATIENT_SAMPLE_METADATA,
    script:
        "../src/convert_PathSeq_output_to_read_counts.py"

#
# rule combine_plate_tests:
#     input:
#         PLATE_WILCOX_MARKERS.format(patient="{patient}", method="{method}", celltype="{celltype}",
#                                     celltype_of_interest="{celltype_of_interest}", tax_level="{tax_level}",
#                                     norm="{norm}", infected_plate="{infected_plate1}", control_plate="{control_plate1}"),
#         PLATE_WILCOX_MARKERS.format(patient="{patient}", method="{method}", celltype="{celltype}",
#                                     celltype_of_interest="{celltype_of_interest}", tax_level="{tax_level}",
#                                     norm="{norm}", infected_plate="{infected_plate1}", control_plate="{control_plate2}"),
#         PLATE_WILCOX_MARKERS.format(patient="{patient}", method="{method}", celltype="{celltype}",
#                                     celltype_of_interest="{celltype_of_interest}", tax_level="{tax_level}",
#                                     norm="{norm}", infected_plate="{infected_plate2}", control_plate="{control_plate1}"),
#         PLATE_WILCOX_MARKERS.format(patient="{patient}", method="{method}", celltype="{celltype}",
#                                     celltype_of_interest="{celltype_of_interest}", tax_level="{tax_level}",
#                                     norm="{norm}", infected_plate="{infected_plate2}", control_plate="{control_plate2}"),
#     output:
#         COMBINED_PLATE_WILCOX_MARKERS
#     script:
#         "src/combine_plate_tests.py"
#
#
# rule calculate_markers_spikein_plate_test:
#     wildcard_constraints:
#         norm="spike"
#     params:
#         spike=SPIKE_PREFIX
#     input:
#         PATIENT_MICROBE_READ_TABLE,
#         PATIENT_SAMPLE_METADATA,
#         STAR_READCOUNT_TABLE
#     output:
#         PLATE_TTEST_MARKERS,
#         PLATE_WILCOX_MARKERS
#     script:
#         "src/run_scran_marker_analysis_spikein_plate.R"
#
# rule calculate_markers_plate_test:
#     wildcard_constraints:
#         norm="deconv"
#     input:
#         PATIENT_MICROBE_READ_TABLE,
#         PATIENT_SAMPLE_METADATA
#     output:
#         PLATE_TTEST_MARKERS,
#         PLATE_WILCOX_MARKERS
#     script:
#         "src/run_scran_marker_analysis_plate.R"




# rule combine_filter_metrics:
#     input:
#         "data/samples.tsv",
#     output:
#         COMBINED_FILTER_METRICS
#     script:
#         "../src/combine_filter_metrics.py"
#
# rule download_filter_metrics:
#     shell:
#         "rsync -avc --include='filter-metrics.txt' --include='*/' --exclude='*' biowulf:/data/Robinson-SB/scRNA-seq-microbe-identification/Aulicino2018/identify-microbes-workflow/output/PathSeq/ filter-metrics/"

# rsync -avc --include='filter-metrics.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/Aulicino2018/identify-microbes-workflow/output/ data/

# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/SB-SS2/output/ data/

# rsync -avc --include='barcodes.tsv' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/SB-SS2/output/ data/
# rsync -avc --include='features.tsv' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/SB-SS2/output/ data/
# rsync -avc --include='matrix.mtx' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/SB-SS2/output/ data/
