from os.path import join

wildcard_constraints:
    tax_level="root|superkingdom|phylum|class|order|family|genus|species|no_rank",
    patient="S53|S57|S61|S65",
    celltype="Tumor|celltype1|celltype2"
# include: "../rules/common.smk"

MICROBE_READ_TABLE = join("output", "{tax_level}_{method}_microbe_reads.tsv")
SAMPLE_METADATA = join("output", "{tax_level}_{method}_sample_metadata.tsv")
PATIENT_MICROBE_READ_TABLE = join("output", "{patient}_{tax_level}_{method}_microbe_reads.tsv")
PATIENT_SAMPLE_METADATA = join("output", "{patient}_{tax_level}_{method}_metadata.tsv")
# BINOM_MARKERS = join("output", "{patient}_{tax_level}_{method}_{norm}_binomial_markers.tsv")
BINOM_PATIENT_MARKERS = join("output", "binomial-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{pvaltype}.tsv")

# ["S53", "S57", "S61", "S65"]
rule all:
    input:
        expand(PATIENT_MICROBE_READ_TABLE, patient="S53", tax_level="genus", method="PathSeq"),
        expand(BINOM_PATIENT_MARKERS, patient=["S65"],
               tax_level=["species", "genus"], method="PathSeq", pvaltype="any",
               celltype="celltype1", celltype_of_interest="NK/ILCs"),


rule calculate_patient_markers:
    input:
        PATIENT_MICROBE_READ_TABLE,
        PATIENT_SAMPLE_METADATA
    output:
        BINOM_PATIENT_MARKERS
    script:
        "../src/run_scran_binomial_marker_analysis.R"

rule filter_read_table_by_patient:
    input:
        MICROBE_READ_TABLE,
        SAMPLE_METADATA
    output:
        PATIENT_MICROBE_READ_TABLE,
        PATIENT_SAMPLE_METADATA
    script:
        "../src/split_read_matrices_by_patient.py"

rule convert_PathSeq_to_readcounts:
    wildcard_constraints:
        method="PathSeq"
    params:
        join("data", "PathSeq", "{}-{}-{}", "pathseq.txt")
    input:
        "data/units.tsv"
    output:
        MICROBE_READ_TABLE,
        SAMPLE_METADATA
    script:
        "src/convert_PathSeq_output_to_read_counts.py"





# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/Paulson2018/output/ data/



# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/Simmons-Collaboration/output/ data/
