from os.path import join

wildcard_constraints:
    patient="H[0-9][0-9]|C[0-9][0-9]",
    celltype="Tumor|celltype1|celltype2"

include: "../rules/common.smk"
include: "../rules/analysis-10x.smk"


rule all:
    input:
        expand(SAMPLE_FISHER_EXACT, patient="H73", sample=["H73a", "H73b"],
        tax_level="genus", celltype="Tumor", celltype_of_interest="Tumor",
        minprop=0, min_umis=2,
        celltype_comparison="nonTumor", method="PathSeq", kingdom="All")
