from os.path import join
import pandas as pd

patients = ['MGH107', 'MGH42', 'MGH43', 'MGH44', 'MGH45', 'MGH56', 'MGH64'] # MGH57, 'MGH103', 'MGH61'

EDGER_RESULTS = join("output", "{tax_level}_edgeR_{norm_method}_results_{patient}-{celltype}.tsv")
TTEST_MARKERS = join("output", "t-test-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}.tsv")
WILCOX_MARKERS = join("output", "wilcox-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}.tsv")
BINOM_MARKERS = join("output", "binom-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{method}-{norm}.tsv")


include: "../rules/common.smk"
include: "../rules/stats.smk"
include: "../rules/plate.smk"
include: "../rules/plotting.smk"

rule all:
    input:
        expand(DECONV_NORM_PLOT, microbe=["Klebsiella"], patient="MGH44", method="PathSeq", celltype="celltype1", tax_level="genus"),
        # expand(DECONV_NORM_PLOT, microbe="Plasmodium", patient="MGH43", method="PathSeq", celltype="celltype1", tax_level="genus"),
        # expand(DECONV_NORM_PLOT, microbe="Pseudomonas", patient=["MGH44"], method="PathSeq", celltype="celltype1", tax_level="genus"),
        #expand(DECONV_NORM_PLOT, microbe="Corynebacterium", patient="MGH107", method="PathSeq", celltype="celltype1", tax_level="genus"),
        #expand(DECONV_NORM_PLOT, microbe="Bifidobacteriaceae", patient="MGH56", method="PathSeq", celltype="celltype1", tax_level="family"),
        expand(TTEST_MARKERS, patient=patients, celltype="celltype1", celltype_of_interest="Microglia", tax_level=["genus", "species"], method="PathSeq", norm="deconv"),
        # expand(MICROBE_READ_TABLE, method="PathSeq", tax_level=["genus", "family"])


# rules for processing the data
rule convert_PathSeq_to_read_counts:
    params:
        join("data", "PathSeq", "{}-{}", "pathseq.txt")
    input:
        "data/patients.tsv",
        "data/samples.tsv"
    output:
        MICROBE_READ_TABLE,
        SAMPLE_METADATA
    script:
        "src/convert_PathSeq_output_to_read_counts.py"



# download PathSeq files
# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/Venteicher2017/identify-microbes-workflow/output/ data/
