from os.path import join
import pandas as pd

wildcard_constraints:
    patient="P0104|P0411|P0413|P0720|P0728|P0825|P1212"


patients = ["P0104", "P0411", "P0413", "P0720", "P0728", "P0825", "P1212"]
# exclude P1228 because only three tumor cells

TTEST_MARKERS = join("output", "t-test-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{kingdom}-{method}-{norm}-{pvaltype}.tsv")
WILCOX_MARKERS = join("output", "wilcox-{patient}-{celltype}-{celltype_of_interest}-{tax_level}-{kingdom}-{method}-{norm}-{pvaltype}.tsv")


include: "../rules/common.smk"
include: "../rules/stats.smk"
include: "../rules/plotting.smk"


rule all:
    input:
        expand(WILCOX_MARKERS, patient=patients, kingdom="Bacteria",
               tax_level="genus", celltype="Tumor", celltype_of_interest="Tumor",
               norm=["deconv"], method="PathSeq", pvaltype="all"),
        expand(DECONV_NORM_PLOT, patient="P1212", celltype=["celltype1"],
               kingdom="Bacteria", tax_level="genus", method="PathSeq",
               microbe="Fusobacterium"),

rule convert_PathSeq_to_read_counts:
    wildcard_constraints:
        method="PathSeq"
    params:
        join("data", "PathSeq", "{}-{}", "pathseq.txt")
    input:
        "data/patients.tsv",
        "data/samples.tsv"
    output:
        MICROBE_READ_TABLE,
        SAMPLE_METADATA
    script:
        "../src/convert_PathSeq_output_to_read_counts.py"

# download PathSeq files
# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/scRNA-seq-microbe-identification/Zhang2020/output/ data/
