from os.path import join
import pandas as pd

cells = pd.read_csv("data/units.tsv", sep="\t")


wildcard_constraints:
    celltype="Tumor|celltype1",
    patient="|".join(cells["patient"].unique())

include: "../rules/common.smk"
include: "../rules/analysis-10x.smk"



patients = cells["patient"].unique()
samples = cells[["patient", "sample"]].drop_duplicates()
tumor_samples = ["Sample{}a".format(x) for x in range(1,10)]
samples = samples.loc[samples["sample"].isin(tumor_samples)]

# exclude "SC001" for now - no tumors cells processed
rule all:
    input:
        expand(PATIENT_BINOM_MARKERS, patient=patients,
               celltype="Tumor", celltype_of_interest="Tumor", celltype_comparison="nonTumor",
               tax_level=["class", "order", "family", "genus", "species"],
               lfc=0, block="sample", direction=["up", "down"], minprop="0.01",
               method="PathSeq", pvaltype="any", kingdom=["All"]),
        expand(SAMPLE_BINOM_MARKERS, zip, patient=samples["patient"], sample=samples["sample"],
               celltype=["Tumor"]*samples.shape[0], celltype_of_interest=["Tumor"]*samples.shape[0],
               celltype_comparison=["nonTumor"]*samples.shape[0],
               tax_level=["genus"]*samples.shape[0],
               lfc=[0]*samples.shape[0], block=["sample"]*samples.shape[0],
               method=["PathSeq"]*samples.shape[0], pvaltype=["any"]*samples.shape[0],
               kingdom=["All"]*samples.shape[0], direction=["up"]*samples.shape[0],
               minprop=["0.01"]*samples.shape[0]),
        # expand(SAMPLE_BINOM_MARKERS, patient="SC028", sample="Sample6a",
        #        celltype="celltype1", celltype_of_interest="Tumor", celltype_comparison="Immune",
        #        tax_level=["class", "order", "family", "genus", "species"],
        #        lfc=0, block="sample",
        #        method="PathSeq", pvaltype="any", kingdom=["Viruses", "Bacteria"]),


rule plot_figures:
    input:
        expand(SAMPLE_BINOM_PLOT, patient=["SC019"], sample="Sample2a", celltype="Tumor",
               celltype_of_interest="Tumor", celltype_comparison="nonTumor",
               tax_level=["species"], block="sample", kingdom="Bacteria", lfc=0,
               method="PathSeq", pvaltype="all", microbe_of_interest="Hathewaya_histolytica"),
        expand(SAMPLE_BINOM_PLOT, patient=["SC028"], sample="Sample6a", celltype="Tumor",
               celltype_of_interest="Tumor", celltype_comparison="nonTumor",
               tax_level=["class"], block="sample", kingdom="Bacteria", lfc=0,
               method="PathSeq", pvaltype="all", microbe_of_interest="Fusobacteriia"),





# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Lee2020/output/ data/
# rsync -avc --include='*-scores.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Lee2020/output/ data/
# rsync -avc --include='raw_feature_bc_matrix.h5' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Lee2020/ data/
