from os.path import join

wildcard_constraints:
    patient="2586-4|9245-3",
    celltype="Tumor|celltype1|celltype2",
    microbe_of_interest="Human_polyomavirus_5",

include: "../rules/common.smk"
include: "../rules/analysis-10x.smk"
#include: "../rules/hFDR.smk"


#FIGURE4A_extended = join("output", "plots", "{patient}", "figure3b_extended_{microbe_of_interest}_{celltype}_{celltype_of_interest}_{celltype_comparison}_{tax_level}_{kingdom}_{method}.pdf")
COHORT_MICROBE_READ_TABLE = join("output", "All", "species_PathSeq_All_reads.tsv")
COHORT_SAMPLE_METADATA = join("output", "All", "PathSeq_metadata.tsv")
COHORT_PATHSEQ_TAXID_MAP = join("output", "All", "tax_id_map_All_PathSeq.tsv")
#FIG_PERCENT_POSITIVE_PLOT = join("output", "plots", "Figure_percent_positive.pdf")
FIGURE_S2B = join("output", "plots", "Figure_S2B.pdf")
FIGURE_S2F = join("output", "plots", "Figure_S2F.pdf")


rule all:
    input:
        FIGURE_S2F,
        FIGURE_S2B,
        expand(SAMPLE_FISHER_EXACT, patient="9245-3", sample="RelapseD565Tumor",
        tax_level="genus", celltype="Tumor", celltype_of_interest="Tumor",
        minprop=0, min_umis=2,
        celltype_comparison="nonTumor", method="PathSeq", kingdom="All")

# plot % of infected cells by cell-type for patient 9245-3
rule plot_figure_S2F:
    input:
        SAMPLE_MICROBE_READ_TABLE.format(patient="9245-3", sample="RelapseD565Tumor", tax_level="species", method="PathSeq", kingdom="All"),
        PATIENT_SAMPLE_METADATA.format(patient="9245-3", method="PathSeq"),
        PATIENT_PATHSEQ_TAXID_MAP.format(patient="9245-3", method="PathSeq", kingdom="All"),
    output:
        FIGURE_S2F
    script:
        "src/plot_figure_S2F.R"

# rule plot_chemistry_read_difference:
#     input:
#         COHORT_MICROBE_READ_TABLE,
#         COHORT_SAMPLE_METADATA,
#         COHORT_PATHSEQ_TAXID_MAP
#     output:
#         FIG_PERCENT_POSITIVE_PLOT
#     script:
#         "src/plot_chemistry_percent_positive.R"

# plot the number of UMIs by sample (and chemistry)
rule plot_figure_S2B:
    input:
        COHORT_MICROBE_READ_TABLE,
        COHORT_SAMPLE_METADATA,
        COHORT_PATHSEQ_TAXID_MAP
    output:
        FIGURE_S2B
    script:
        "src/plot_figure_S2B.R"


rule combine_patients:
    input:
        PATIENT_MICROBE_READ_TABLE.format(patient="9245-3", tax_level="species", kingdom="All", method="PathSeq"),
        PATIENT_MICROBE_READ_TABLE.format(patient="2586-4", tax_level="species", kingdom="All", method="PathSeq"),
        PATIENT_SAMPLE_METADATA.format(patient="9245-3", method="PathSeq"),
        PATIENT_SAMPLE_METADATA.format(patient="2586-4", method="PathSeq"),
        PATIENT_PATHSEQ_TAXID_MAP.format(patient="9245-3", kingdom="All", method="PathSeq"),
        PATIENT_PATHSEQ_TAXID_MAP.format(patient="2586-4", kingdom="All", method="PathSeq")
    output:
        COHORT_MICROBE_READ_TABLE,
        COHORT_SAMPLE_METADATA,
        COHORT_PATHSEQ_TAXID_MAP,
    script:
        "src/combine_patient_data.py"




# rsync -avc --include='pathseq.txt' --include='*/' --exclude='*' helix:/data/Robinson-SB/CSI-Microbes-identification/Paulson2018/output/ raw/
